#!/usr/bin/env python3
"""
Upload PDB metadata TSVs to MinIO and run data_lakehouse_ingest.

Prerequisites:
  - TSVs generated by download_pdb_data.py
  - Active Spark session on JupyterHub

Usage:
  python ingest_pdb.py [--upload-only] [--ingest-only]
"""

import argparse
import json
import os

from berdl_notebook_utils.berdl_settings import get_settings
from berdl_notebook_utils.minio_governance import get_minio_credentials
from data_lakehouse_ingest import ingest
from minio import Minio

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = "/pscratch/sd/p/psdehal/pdb_collection"
BUCKET = "cdm-lake"
BRONZE_PREFIX = "tenant-general-warehouse/kescience/datasets/pdb"

FILES_TO_UPLOAD = [
    ("pdb_entries.tsv", DATA_DIR),
    ("pdb_uniprot_mapping.tsv", DATA_DIR),
    ("pdb_collection.json", SCRIPT_DIR),
]

# Load ingestion config from JSON file
with open(os.path.join(SCRIPT_DIR, "pdb_collection.json")) as f:
    INGEST_CONFIG = json.load(f)


def get_minio_client():
    """Create MinIO client with BERDL credentials."""
    creds = get_minio_credentials()
    settings = get_settings()
    endpoint = settings.MINIO_ENDPOINT_URL.replace("https://", "").replace("http://", "")
    client = Minio(
        endpoint=endpoint,
        access_key=creds.access_key,
        secret_key=creds.secret_key,
        secure=True,
    )
    print(f"MinIO client ready (user: {creds.username})")
    return client


def upload_files(minio_client):
    """Upload TSVs and config JSON to MinIO bronze storage."""
    print(f"\nUploading to s3a://{BUCKET}/{BRONZE_PREFIX}/")
    for fname, local_dir in FILES_TO_UPLOAD:
        local_path = os.path.join(local_dir, fname)
        if not os.path.exists(local_path):
            print(f"  SKIP {fname} (not found at {local_path})")
            continue
        remote_key = f"{BRONZE_PREFIX}/{fname}"
        fsize = os.path.getsize(local_path)
        print(f"  Uploading {fname} ({fsize:,} bytes)...", end="", flush=True)
        minio_client.fput_object(BUCKET, remote_key, local_path)
        print(" done")

    # Verify uploads
    print(f"\nVerifying uploads:")
    objects = list(minio_client.list_objects(BUCKET, prefix=BRONZE_PREFIX, recursive=True))
    for obj in objects:
        print(f"  {obj.object_name.split('/')[-1]:40s} {obj.size:>14,} bytes")


def run_ingestion(minio_client):
    """Run data_lakehouse_ingest with config."""
    print(f"\nRunning data_lakehouse_ingest ({len(INGEST_CONFIG['tables'])} tables)...")
    report = ingest(INGEST_CONFIG, minio_client=minio_client)

    print(f"\n{'=' * 60}")
    print(f"INGESTION REPORT")
    print(f"{'=' * 60}")
    print(f"Success: {report['success']}")
    print(f"Duration: {report.get('duration_sec', 'N/A')}")
    for t in report.get("tables", []):
        print(
            f"  {t['name']:30s} {str(t.get('rows_written', '?')):>14s} rows  [{t.get('status', '?')}]"
        )
    if report.get("errors"):
        for e in report["errors"]:
            print(f"  ERROR: {e}")
    return report


def main():
    parser = argparse.ArgumentParser(description="Upload and ingest PDB metadata into BERDL")
    parser.add_argument("--upload-only", action="store_true", help="Only upload, skip ingestion")
    parser.add_argument("--ingest-only", action="store_true", help="Only ingest, skip upload")
    args = parser.parse_args()

    minio_client = get_minio_client()

    if not args.ingest_only:
        upload_files(minio_client)

    if not args.upload_only:
        run_ingestion(minio_client)


if __name__ == "__main__":
    main()
