#!/usr/bin/env python3
"""
Upload AlphaFold metadata TSVs to MinIO and run data_lakehouse_ingest.

Uploads prepared TSVs to MinIO bronze storage, then runs the BERDL ingest
pipeline to create Delta Lake tables in the kescience_alphafold database.

Prerequisites:
  - TSVs generated by prepare_alphafold_tables.py
  - Active Spark session on JupyterHub

Usage:
  python ingest_alphafold.py [--upload-only] [--ingest-only]
"""

import argparse
import os

from berdl_notebook_utils.berdl_settings import get_settings
from berdl_notebook_utils.minio_governance import get_minio_credentials
from data_lakehouse_ingest import ingest
from minio import Minio

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = "/pscratch/sd/p/psdehal/alphafold_collection"
BUCKET = "cdm-lake"
BRONZE_PREFIX = "tenant-general-warehouse/kescience/datasets/alphafold"

FILES_TO_UPLOAD = [
    ("alphafold_entries.tsv", DATA_DIR),
    ("alphafold_msa_depths.tsv", DATA_DIR),
    ("alphafold_collection.json", SCRIPT_DIR),
]

INGEST_CONFIG = {
    "tenant": "kescience",
    "dataset": "alphafold",
    "paths": {
        "bronze_base": f"s3a://{BUCKET}/{BRONZE_PREFIX}/",
        "silver_base": "s3a://cdm-lake/tenant-sql-warehouse/kescience/kescience_alphafold.db",
    },
    "defaults": {"tsv": {"header": True, "delimiter": "\t", "inferSchema": False}},
    "tables": [
        {
            "name": "alphafold_entries",
            "format": "tsv",
            "bronze_path": f"s3a://{BUCKET}/{BRONZE_PREFIX}/alphafold_entries.tsv",
            "schema_sql": (
                "uniprot_accession STRING, first_residue INT, last_residue INT, "
                "alphafold_id STRING, model_version INT"
            ),
        },
        {
            "name": "alphafold_msa_depths",
            "format": "tsv",
            "bronze_path": f"s3a://{BUCKET}/{BRONZE_PREFIX}/alphafold_msa_depths.tsv",
            "schema_sql": "uniprot_accession STRING, msa_depth INT",
        },
    ],
}


def get_minio_client():
    """Create MinIO client with BERDL credentials."""
    creds = get_minio_credentials()
    settings = get_settings()
    endpoint = settings.MINIO_ENDPOINT_URL.replace("https://", "").replace(
        "http://", ""
    )
    client = Minio(
        endpoint=endpoint,
        access_key=creds.access_key,
        secret_key=creds.secret_key,
        secure=True,
    )
    print(f"MinIO client ready (user: {creds.username})")
    return client


def upload_files(minio_client):
    """Upload TSVs and config JSON to MinIO bronze storage."""
    print(f"\nUploading to s3a://{BUCKET}/{BRONZE_PREFIX}/")
    for fname, local_dir in FILES_TO_UPLOAD:
        local_path = os.path.join(local_dir, fname)
        if not os.path.exists(local_path):
            print(f"  SKIP {fname} (not found at {local_path})")
            continue
        remote_key = f"{BRONZE_PREFIX}/{fname}"
        fsize = os.path.getsize(local_path)
        print(f"  Uploading {fname} ({fsize:,} bytes)...", end="", flush=True)
        minio_client.fput_object(BUCKET, remote_key, local_path)
        print(" done")

    # Verify uploads
    print(f"\nVerifying uploads:")
    objects = list(
        minio_client.list_objects(BUCKET, prefix=BRONZE_PREFIX, recursive=True)
    )
    for obj in objects:
        print(f"  {obj.object_name.split('/')[-1]:40s} {obj.size:>14,} bytes")


def run_ingestion(minio_client):
    """Run data_lakehouse_ingest with inline config."""
    print(f"\nRunning data_lakehouse_ingest (inline config, 2 tables)...")
    print("NOTE: alphafold_entries.tsv is ~8 GB — this may take a while.\n")
    report = ingest(INGEST_CONFIG, minio_client=minio_client)

    # Summary
    print(f"\n{'=' * 60}")
    print(f"INGESTION REPORT")
    print(f"{'=' * 60}")
    print(f"Success: {report['success']}")
    print(f"Duration: {report.get('duration_sec', 'N/A')}")
    for t in report.get("tables", []):
        print(
            f"  {t['name']:30s} {str(t.get('rows_written', '?')):>14s} rows  [{t.get('status', '?')}]"
        )
    if report.get("errors"):
        for e in report["errors"]:
            print(f"  ERROR: {e}")
    return report


def main():
    parser = argparse.ArgumentParser(
        description="Upload and ingest AlphaFold metadata into BERDL"
    )
    parser.add_argument(
        "--upload-only", action="store_true", help="Only upload, skip ingestion"
    )
    parser.add_argument(
        "--ingest-only", action="store_true", help="Only ingest, skip upload"
    )
    args = parser.parse_args()

    minio_client = get_minio_client()

    if not args.ingest_only:
        upload_files(minio_client)

    if not args.upload_only:
        run_ingestion(minio_client)


if __name__ == "__main__":
    main()
