#!/usr/bin/env python3
"""
Upload BacDive TSV files to MinIO and run data_lakehouse_ingest.

Prerequisites:
  - TSV files generated by flatten_bacdive.py
  - bacdive.json config in this directory
  - Active Spark session on JupyterHub
"""

import os
import json
from berdl_notebook_utils.minio_governance import get_minio_credentials
from berdl_notebook_utils.berdl_settings import get_settings
from minio import Minio
from data_lakehouse_ingest import ingest

LOCAL_DIR = os.path.dirname(os.path.abspath(__file__))
BUCKET = "cdm-lake"
BRONZE_PREFIX = "tenant-general-warehouse/kescience/datasets/bacdive"

FILES_TO_UPLOAD = [
    "strain.tsv",
    "taxonomy.tsv",
    "culture_condition.tsv",
    "isolation.tsv",
    "physiology.tsv",
    "metabolite_utilization.tsv",
    "sequence_info.tsv",
    "enzyme.tsv",
    "bacdive.json",
]


def main():
    # Get MinIO credentials
    creds = get_minio_credentials()
    settings = get_settings()
    endpoint = settings.MINIO_ENDPOINT_URL.replace("https://", "").replace("http://", "")

    minio_client = Minio(
        endpoint=endpoint,
        access_key=creds.access_key,
        secret_key=creds.secret_key,
        secure=True,
    )
    print(f"MinIO client ready (user: {creds.username})")

    # Upload files
    print(f"\nUploading to s3a://{BUCKET}/{BRONZE_PREFIX}/")
    for fname in FILES_TO_UPLOAD:
        local_path = os.path.join(LOCAL_DIR, fname)
        if not os.path.exists(local_path):
            print(f"  SKIP {fname} (not found)")
            continue
        remote_key = f"{BRONZE_PREFIX}/{fname}"
        fsize = os.path.getsize(local_path)
        minio_client.fput_object(BUCKET, remote_key, local_path)
        print(f"  Uploaded {fname} ({fsize:,} bytes)")

    # Verify uploads
    print(f"\nVerifying uploads:")
    objects = list(minio_client.list_objects(BUCKET, prefix=BRONZE_PREFIX, recursive=True))
    for obj in objects:
        print(f"  {obj.object_name.split('/')[-1]:40s} {obj.size:>12,} bytes")

    # Run ingestion
    print(f"\nRunning data_lakehouse_ingest...")
    cfg_path = f"s3a://{BUCKET}/{BRONZE_PREFIX}/bacdive.json"
    report = ingest(cfg_path, minio_client=minio_client)

    # Summary
    print(f"\n{'='*60}")
    print(f"INGESTION REPORT")
    print(f"{'='*60}")
    print(f"Success: {report['success']}")
    print(f"Duration: {report['duration_sec']:.1f}s")
    for t in report.get("tables", []):
        print(f"  {t['name']:30s} {t['rows_written']:>8,} rows  [{t['status']}]")
    if report.get("errors"):
        for e in report["errors"]:
            print(f"  ERROR: {e}")


if __name__ == "__main__":
    main()
