#!/usr/bin/env python3
"""
Upload bakta annotation tables to MinIO and run data_lakehouse_ingest.

Uploads final TSVs and config JSON to MinIO bronze storage, then
runs the BERDL ingest pipeline to create Delta Lake tables in
the kbase_ke_pangenome database.

Prerequisites:
  - Final TSVs generated by combine_tables.py
  - bakta_reannotation.json config in this directory
  - Active Spark session on JupyterHub

Usage:
  python ingest_bakta.py
"""

import os

from berdl_notebook_utils.berdl_settings import get_settings
from berdl_notebook_utils.minio_governance import get_minio_credentials
from data_lakehouse_ingest import ingest
from minio import Minio

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
FINAL_DIR = "/pscratch/sd/p/psdehal/bakta_reannotation/tables/final"
BUCKET = "cdm-lake"
BRONZE_PREFIX = "tenant-general-warehouse/kbase_ke/datasets/pangenome/bakta"

FILES_TO_UPLOAD = [
    ("bakta_annotations.tsv", FINAL_DIR),
    ("bakta_db_xrefs.tsv", FINAL_DIR),
    ("bakta_pfam_domains.tsv", FINAL_DIR),
    ("bakta_amr.tsv", FINAL_DIR),
    ("bakta_reannotation.json", SCRIPT_DIR),
]


def main():
    # Get MinIO credentials
    creds = get_minio_credentials()
    settings = get_settings()
    endpoint = settings.MINIO_ENDPOINT_URL.replace("https://", "").replace(
        "http://", ""
    )

    minio_client = Minio(
        endpoint=endpoint,
        access_key=creds.access_key,
        secret_key=creds.secret_key,
        secure=True,
    )
    print(f"MinIO client ready (user: {creds.username})")

    # Upload files
    print(f"\nUploading to s3a://{BUCKET}/{BRONZE_PREFIX}/")
    for fname, local_dir in FILES_TO_UPLOAD:
        local_path = os.path.join(local_dir, fname)
        if not os.path.exists(local_path):
            print(f"  SKIP {fname} (not found at {local_path})")
            continue
        remote_key = f"{BRONZE_PREFIX}/{fname}"
        fsize = os.path.getsize(local_path)
        print(f"  Uploading {fname} ({fsize:,} bytes)...", end="", flush=True)
        minio_client.fput_object(BUCKET, remote_key, local_path)
        print(" done")

    # Verify uploads
    print(f"\nVerifying uploads:")
    objects = list(
        minio_client.list_objects(BUCKET, prefix=BRONZE_PREFIX, recursive=True)
    )
    for obj in objects:
        print(f"  {obj.object_name.split('/')[-1]:40s} {obj.size:>14,} bytes")

    # Run ingestion
    print(f"\nRunning data_lakehouse_ingest...")
    cfg_path = f"s3a://{BUCKET}/{BRONZE_PREFIX}/bakta_reannotation.json"
    report = ingest(cfg_path, minio_client=minio_client)

    # Summary
    print(f"\n{'=' * 60}")
    print(f"INGESTION REPORT")
    print(f"{'=' * 60}")
    print(f"Success: {report['success']}")
    print(f"Duration: {report['duration_sec']:.1f}s")
    for t in report.get("tables", []):
        print(
            f"  {t['name']:30s} {t['rows_written']:>14,} rows  [{t['status']}]"
        )
    if report.get("errors"):
        for e in report["errors"]:
            print(f"  ERROR: {e}")


if __name__ == "__main__":
    main()
