#!/usr/bin/env python3
"""
Generate visualization scripts for Coot, PyMOL, and ChimeraX.

Produces parameterized scripts from validation outlier data for human-in-the-loop
model inspection and publication figure generation.

Usage:
  # Generate all scripts for a validation report
  python generate_scripts.py --report validation.json --output-dir scripts/

  # Generate Ramachandran plot from ramalyze output
  python generate_scripts.py --ramalyze ramalyze.out --output-dir figures/

  # As a library
  from generate_scripts import generate_coot_outlier_script
  generate_coot_outlier_script(outliers, "model.pdb", output_path="coot_outliers.py")
"""

import argparse
import json
import os
import sys


def generate_coot_outlier_script(outliers, model_path, data_path=None,
                                  map_path=None, output_path="coot_outliers.py"):
    """Generate a Coot Python script that navigates to validation outliers.

    Args:
        outliers: list of dicts with 'residue', 'type', and optionally 'chain', 'resnum'
        model_path: path to PDB model file
        data_path: path to MTZ data file (X-ray)
        map_path: path to MRC map file (cryo-EM)
        output_path: where to write the script
    """
    lines = [
        "# coot_outliers.py — generated by phenix agent",
        "# Usage: coot --script coot_outliers.py",
        "#",
        "# Navigate validation outliers with Ctrl+Right/Left arrow",
        "",
        "import coot",
        "",
        f'model_imol = coot.read_pdb("{model_path}")',
    ]

    if data_path:
        lines.append(f'map_imol = coot.auto_read_make_and_draw_maps("{data_path}")')
    elif map_path:
        lines.append(f'map_imol = coot.handle_read_ccp4_map("{map_path}", 0)')
        lines.append("coot.set_contour_level_absolute(map_imol, 0.02)")

    lines.append("")
    lines.append("# Validation outliers")
    lines.append("outliers = [")

    for o in outliers:
        residue = o.get("residue", "?")
        issue = o.get("type", "unknown")
        # Parse chain and residue number from residue string like "A:45:LEU" or "A  45  LEU"
        chain, resnum, resname = _parse_residue(residue)
        lines.append(f'    ("{chain}", {resnum}, "{resname}", "{issue}"),')

    lines.append("]")
    lines.append("")
    lines.append("if outliers:")
    lines.append("    chain, resno, resname, issue = outliers[0]")
    lines.append('    coot.set_go_to_atom_chain_residue_atom_name(chain, resno, " CA ")')
    lines.append(f'    print(f"Outlier 1/{{len(outliers)}}: {{chain}}:{{resname}}{{resno}} -- {{issue}}")')
    lines.append('    print("Use Ctrl+Right/Left arrow to navigate between outliers")')
    lines.append("else:")
    lines.append('    print("No outliers found — model looks good!")')

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return output_path


def generate_pymol_validation_script(outliers, model_path,
                                      output_path="pymol_validation.pml"):
    """Generate a PyMOL script that highlights validation outliers.

    Args:
        outliers: list of dicts with 'residue' and 'type'
        model_path: path to PDB model file
        output_path: where to write the script
    """
    # Collect outlier residue numbers
    rama_resnums = []
    rota_resnums = []
    clash_resnums = []

    for o in outliers:
        _, resnum, _ = _parse_residue(o.get("residue", ""))
        if resnum == 0:
            continue
        otype = o.get("type", "")
        if "ramachandran" in otype:
            rama_resnums.append(str(resnum))
        elif "rotamer" in otype:
            rota_resnums.append(str(resnum))
        else:
            clash_resnums.append(str(resnum))

    lines = [
        f"# pymol_validation.pml — generated by phenix agent",
        f"# Usage: pymol pymol_validation.pml",
        f"# Headless: pymol -c pymol_validation.pml",
        "",
        f"load {model_path}, structure",
        "",
        "# Base display",
        "hide everything",
        "show cartoon, structure",
        "color white, structure",
        "",
    ]

    if rama_resnums:
        sel = "+".join(rama_resnums)
        lines.extend([
            f"# Ramachandran outliers (red)",
            f"select rama_outliers, resi {sel}",
            "color red, rama_outliers",
            "show sticks, rama_outliers",
            "",
        ])

    if rota_resnums:
        sel = "+".join(rota_resnums)
        lines.extend([
            f"# Rotamer outliers (orange)",
            f"select rota_outliers, resi {sel}",
            "color orange, rota_outliers",
            "show sticks, rota_outliers",
            "",
        ])

    if clash_resnums:
        sel = "+".join(clash_resnums)
        lines.extend([
            f"# Clash outliers (magenta)",
            f"select clash_outliers, resi {sel}",
            "color magenta, clash_outliers",
            "show sticks, clash_outliers",
            "",
        ])

    lines.extend([
        "# Rendering settings",
        "bg_color white",
        "set ray_opaque_background, 1",
        "set antialias, 2",
        "set ray_shadows, 0",
        "",
        "# Render (uncomment to save)",
        "# ray 2400, 1800",
        "# png validation_figure.png, dpi=300",
    ])

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return output_path


def generate_chimerax_session(model_path, map_path=None, outliers=None,
                               output_path="chimerax_session.cxc"):
    """Generate a ChimeraX command script.

    Args:
        model_path: path to PDB model file
        map_path: path to MRC map file (optional)
        outliers: list of outlier dicts (optional)
        output_path: where to write the script
    """
    lines = [
        "# chimerax_session.cxc — generated by phenix agent",
        "# Usage: chimerax chimerax_session.cxc",
        "",
        f"open {model_path}",
    ]

    if map_path:
        lines.extend([
            f"open {map_path}",
            "",
            "# Map display",
            "volume #2 step 1 level 0.02 color #5588ccaa",
        ])

    lines.extend([
        "",
        "# Model display",
        "cartoon style #1",
        "color bychain #1",
    ])

    if outliers:
        resnums = []
        for o in outliers:
            _, resnum, _ = _parse_residue(o.get("residue", ""))
            if resnum > 0:
                resnums.append(str(resnum))
        if resnums:
            sel = ",".join(resnums)
            lines.extend([
                "",
                "# Highlight outlier residues",
                f"select /A:{sel}",
                "color sel red",
                "show sel atoms",
            ])

    lines.extend([
        "",
        "# View settings",
        "lighting soft",
        "set bgColor white",
        "view",
    ])

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return output_path


def generate_ramachandran_plot(phi_psi_data, output_path="ramachandran.png"):
    """Generate a Ramachandran plot from phi/psi data.

    Args:
        phi_psi_data: list of (phi, psi, is_outlier) tuples
        output_path: where to save the PNG
    """
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("WARNING: matplotlib not available, skipping Ramachandran plot")
        return None

    phi_fav, psi_fav = [], []
    phi_out, psi_out = [], []

    for phi, psi, is_outlier in phi_psi_data:
        if is_outlier:
            phi_out.append(phi)
            psi_out.append(psi)
        else:
            phi_fav.append(phi)
            psi_fav.append(psi)

    fig, ax = plt.subplots(figsize=(8, 8))
    ax.scatter(phi_fav, psi_fav, s=5, c="blue", alpha=0.3, label="Favored/Allowed")
    if phi_out:
        ax.scatter(phi_out, psi_out, s=30, c="red", marker="x", label="Outlier")
    ax.set_xlim(-180, 180)
    ax.set_ylim(-180, 180)
    ax.set_xlabel("Phi (degrees)")
    ax.set_ylabel("Psi (degrees)")
    ax.set_title("Ramachandran Plot")
    ax.legend()
    ax.set_aspect("equal")
    ax.axhline(0, color="gray", linewidth=0.5)
    ax.axvline(0, color="gray", linewidth=0.5)
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.close()
    return output_path


def generate_rfactor_plot(cycles_data, output_path="rfactor_convergence.png"):
    """Generate R-factor convergence plot.

    Args:
        cycles_data: list of dicts with 'cycle', 'r_work', 'r_free' keys
        output_path: where to save the PNG
    """
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("WARNING: matplotlib not available, skipping R-factor plot")
        return None

    cycles = [d["cycle"] for d in cycles_data]
    r_work = [d["r_work"] for d in cycles_data]
    r_free = [d["r_free"] for d in cycles_data]

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(cycles, r_work, "b-o", label="R-work", markersize=6)
    ax.plot(cycles, r_free, "r-o", label="R-free", markersize=6)
    ax.fill_between(cycles, r_work, r_free, alpha=0.15, color="gray", label="R-gap")
    ax.set_xlabel("Refinement Cycle")
    ax.set_ylabel("R-factor")
    ax.set_title("Refinement Convergence")
    ax.legend()
    ax.set_ylim(0, max(max(r_free) * 1.2, 0.4))
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.close()
    return output_path


def parse_ramalyze_file(filepath):
    """Parse phenix.ramalyze output file into phi/psi data.

    Returns list of (phi, psi, is_outlier) tuples.
    """
    data = []
    with open(filepath) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split(":")
            if len(parts) >= 4:
                try:
                    phi = float(parts[1].strip().split(",")[0])
                    psi = float(parts[1].strip().split(",")[1] if "," in parts[1] else parts[2])
                    is_outlier = "OUTLIER" in line
                    data.append((phi, psi, is_outlier))
                except (ValueError, IndexError):
                    pass
    return data


def _parse_residue(residue_str):
    """Parse a residue identifier into (chain, resnum, resname).

    Handles formats like:
      "A:45:LEU"
      "A  45  LEU"
      "A 15 PRO"
    """
    residue_str = residue_str.strip()
    if ":" in residue_str:
        parts = residue_str.split(":")
        chain = parts[0].strip() if parts[0].strip() else "A"
        try:
            resnum = int(parts[1].strip())
        except (ValueError, IndexError):
            resnum = 0
        resname = parts[2].strip() if len(parts) > 2 else "UNK"
    else:
        parts = residue_str.split()
        chain = parts[0] if len(parts) > 0 else "A"
        try:
            resnum = int(parts[1]) if len(parts) > 1 else 0
        except ValueError:
            resnum = 0
        resname = parts[2] if len(parts) > 2 else "UNK"
    return chain, resnum, resname


def main():
    parser = argparse.ArgumentParser(
        description="Generate visualization scripts from validation data"
    )
    parser.add_argument("--report", help="Path to validation report JSON")
    parser.add_argument("--model", help="Path to PDB model")
    parser.add_argument("--data", help="Path to MTZ data (X-ray)")
    parser.add_argument("--map", help="Path to MRC map (cryo-EM)")
    parser.add_argument("--ramalyze", help="Path to phenix.ramalyze output")
    parser.add_argument("--output-dir", default=".", help="Output directory")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    if args.report:
        with open(args.report) as f:
            report = json.load(f)
        outliers = report.get("outliers", [])
        model = args.model or report.get("model", "model.pdb")

        generate_coot_outlier_script(
            outliers, model, data_path=args.data, map_path=args.map,
            output_path=os.path.join(args.output_dir, "coot_outliers.py"),
        )
        print(f"  Generated coot_outliers.py")

        generate_pymol_validation_script(
            outliers, model,
            output_path=os.path.join(args.output_dir, "pymol_validation.pml"),
        )
        print(f"  Generated pymol_validation.pml")

        generate_chimerax_session(
            model, map_path=args.map, outliers=outliers,
            output_path=os.path.join(args.output_dir, "chimerax_session.cxc"),
        )
        print(f"  Generated chimerax_session.cxc")

    if args.ramalyze:
        phi_psi = parse_ramalyze_file(args.ramalyze)
        path = generate_ramachandran_plot(
            phi_psi,
            output_path=os.path.join(args.output_dir, "ramachandran.png"),
        )
        if path:
            print(f"  Generated ramachandran.png")


if __name__ == "__main__":
    main()
